test

diff --git a/shellweb b/shellweb
--- a/shellweb
+++ b/shellweb
@@ -1,7 +1,6 @@
 #!/bin/ksh
 
 set -e
-
 verbose=false
 auth_enabled=false
 if [ `id -u` = 0 ]; then
@@ -18,7 +17,7 @@ usage() {
 }
 
 while getopts "a:d:p:v" OPT; do case $OPT in
-	a)      auth_file=$OPTARG; auth_enabled=true;;
+	a)      authfile=$OPTARG; auth_enabled=true;;
 	d)      root=$OPTARG;;
 	p)      port=$OPTARG;;
 	v)      verbose=true;;
@@ -26,10 +25,12 @@ while getopts "a:d:p:v" OPT; do case $OPT in
 esac; done
 shift $((OPTIND - 1))
 
-authfile=$(readlink -f -- "$authfile")
-if ! [ -r "$authfile" -a -f "$authfile" ]; then
-	echo "could not read file '$authfile'" >&2
-	exit 1
+if [ -n "$authfile" ]; then
+	authfile=$(readlink -f -- "$authfile")
+	if ! [ -r "$authfile" -a -f "$authfile" ]; then
+		echo "could not read file '$authfile'" >&2
+		exit 1
+	fi
 fi
 
 $verbose && echo "root directory is $root" >&2
